### ISSUE TITLE
Varo 0.3.0 breaking changes

### ISSUE THREAD

**Issue by mcdonnelldean** [vtardia/varo-flux#1]
@vtardia 

For 0.3.0 I splitted events and commands. You now manually need to raise events to fire observe handlers. Simply use varo.emit(your_msg). It's a minor change to your logic I think. 

The reason for the split was to speed up things. I found I mostly needed emits to fire to let people know something had changed. It made sense that I could handle what it was they wanted to know.

Let me know if you need any help moving over.

**Comment by vtardia** [comment]
@mcdonnelldean updated without problems, actually only emit is needed now, since the library is based only on observers.

**Comment by mcdonnelldean** [comment]
@vtardia Awesome! Glad to here it. Yeah I'm getting a lot of mileage out of observers. I use them more than acts now :D
